config/routes.rb
Rails.application.routes.draw do
	root 'products#index'

  devise_for :users
	resources :charges
  resources :users
  resources :orders
  resources :carts
  resources :products
    resources :line_items
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
    belongs_to :user
    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum += line_item.total_price
      end
      sum
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    #belongs_to :order

  # LOGIC
   def total_price
     #if valid_quantity_and_price?
       quantity.to_s.to_d * product.price.to_s.to_d
     #else
       #0.0
     #end
   end

  def valid_quantity_and_price?
    !quantity.to_s.strip.empty? && !product.price.to_s.strip.empty?
  end

  # def destroy
  #   @line_item = LineItem.find(params[:id])
  #   @line_item.destroy
  # end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    # enum pay_method: {
    #   'Check' => 0,
    #   'Credit card' => 1,
    #   'Purchase order' => 2
    # }
    belongs_to :user
    # validates :pay_method, :description, presence: true
    # validates :pay_method, inclusion: pay_methods.keys
  
    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum += line_item.total_price
      end
      sum
    end
  
    def self.search(search)
      where('name LIKE ?', "%#{search}%")
    end
end

app/models/product.rb
class Product < ApplicationRecord
    # mount_uploader :picture, ProductPictureUploader
    has_many :line_items, dependent: :destroy
    has_many :orders, through: :line_items
  
    def self.search(search)
      where('name LIKE ?', "%#{search}%")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  after_create :create_cart


  puts "$"*60;puts "user.rb called";puts "$"*60

  has_one_attached :avatar #This is for active storage, to use an avatar picture.

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    # after_create :welcome_send
  has_many :orders
  
   def welcome_send
     UserMailer.welcome_email(self).deliver_now
  end

  def create_cart
    puts self
    puts self.id
    Cart.create!(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find_by(user_id: current_user)
    @line_items = LineItem.where(cart_id: @cart)
    @products = []
    @line_items.each do |line_item|
      @products << Product.find(line_item.product_id)
      end
      puts @products
  end

  def edit
  end

  def update
  end

  def destroy
    
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @amount = 5001
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'EUR',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    puts '$'*60; puts "'home_controller#index' has been called"; puts '$'*60
    #@item_array = Item.all
  end

  
# This method is wrong according to our mentor.
  # def is_connected?(user)
  #   if current_user == user
  #     return true
  #   end
  #   false
  # end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  
  before_action :authenticate_user!

  def index
  end

  def new
    puts "$"*60; puts "line_items#new called"
    product_id = params[:format]
    puts "product_id: "
    puts product_id
    quantity = 1
    puts "quantity: "
    puts quantity
    cart = Cart.all.find_by(user_id: current_user.id)
    puts "cart"
    puts cart
    cart_id = cart.id
    puts "cart_id"
    puts cart_id
    LineItem.create(cart_id: cart_id, product_id: product_id, quantity: quantity)
    redirect_to cart_path(current_user.id)
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    puts "$"*60;puts "product_controller#index"
    @products = Product.all
  end

  def show
    puts "$"*60;puts "product_controller#show"
    puts params
    puts params[:id]
    @product = Product.all.find(params[:id])
    puts "$"*60;puts "@products"
    puts @product
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

 before_action :authenticate_user, only: [:show]
 before_action :is_logged_user

  def show
    @user = current_user
    @user_events = User.find(params[:id]).event_admin
  end

end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

    def is_logged_user
      unless current_user.id == params[:id].to_i
        flash[:danger] = "You can only visit your profile."
        redirect_to root_path
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :is_logged_user

  puts '$'*60; puts "'users_controller' has been called"; puts '$'*60

  def index
    puts '$'*60; puts "'users#index' has been called";puts '$'*60
    @users = User.all
  end

  def show
    puts '$'*60; puts "'users#show' has been called"; puts '$'*60
    @user = current_user
    # Change that, according to our mentor: 
    # unless is_connected?(@user)
    #   flash[:alert] = "Restricted access."
    #   redirect_to root_path
    # end
  end

  private

  def authenticate_user
    puts '$'*60; puts "users_controller#authenticate_user' has been called"; puts '$'*60
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

    def is_logged_user
      puts '$'*60; puts "users_controller#is_logged_user' has been called"; puts '$'*60
      unless current_user.id == params[:id].to_i
        flash[:danger] = "You can only visit your profile."
        redirect_to root_path
      end
  end
  
  def is_connected?(user)
    if current_user == user
      return true
    end
    false
  end

  def create_cart
    puts self
    puts self.id
    Cart.create!(user_id: self.id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/show.html.erb
<!-- source : https://bootsnipp.com/snippets/yP7qe -->
<h2 class="h3 mb-3 font-weight-normal text-center">Cart full of love</h2>
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%">Product</th>
        <th style="width:0%"> </th>
        <th style="width:8%"> </th>
        <th style="width:22%" class="text-center">Price</th>
        <th style="width:20%"></th>
      </tr>
    </thead>
    <%@products.each do |product|%>
      <tbody>
        <tr>
          <td data-th="Product">
            <div class="row">
              <div class="col-sm-2 hidden-xs"><img src="<%=product.picture%>" alt="cat-image" class="img-responsive"/></div>
              <div class="col-sm-10">
                <h4 class="ml-3"><%=product.name%></h4>
                <p class="ml-3"><%=product.description%></p>
              </div>
            </div>
          </td>
          <td data-th="Price"> </td>
          <td data-th="Quantity">
          </td>
          <td data-th="Subtotal" class="text-center"><%=product.price%></td>
          <td class="actions" data-th="">
            <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
            <button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
          </td>
        </tr>
      </tbody>
    <%end%>
    <tfoot>
      <tr class="visible-xs">
        <td class="text-center"><strong> </strong></td>
      </tr>
      <tr>
        <td><a href="<%=products_path%>" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total:  euros</strong></td>
        <td><a href="#" class="btn btn-success">Adopt a cat now <i class="fa fa-angle-right"></i></a></td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/line_items/edit.html.erb
<h1>LineItems#edit</h1>
<p>Find me in app/views/line_items/edit.html.erb</p>

app/views/line_items/index.html.erb
<h1>LineItems#index</h1>
<p>Find me in app/views/line_items/index.html.erb</p>

app/views/line_items/new.html.erb
<h1>LineItems#new</h1>
<p>Find me in app/views/line_items/new.html.erb</p>

app/views/line_items/show.html.erb
<h1>LineItems#show</h1>
<p>Find me in app/views/line_items/show.html.erb</p>

app/views/line_items/update.html.erb
<h1>LineItems#update</h1>
<p>Find me in app/views/line_items/update.html.erb</p>

app/views/products/index.html.erb
<body>
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Nectar de châton</h1>
  <p class="lead"> Découvrez nos merveileux châtons qui raviront votre intérieur de célibataire endurci</p>
</div>
 <br><br>

    <div class="container">

    <div class="row">
            <% @products.each do |n|%>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <img class="card-img-top" src=<%= n.picture %> alt="Card image cap" style="max-width:100%">
                <div class="card-body">
                  <h4 class="card-title"><%=n.name%></h4>
                  <h5><%=n.description%></h5>
                  <p class="card-text"><%=n.price%> € </p>
                <%= link_to "I want this one", product_path(n.id), :class=> "btn btn-outline-primary" %>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Quick view </button>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
             <%end%>
          </div>

</div>
<!-- Button trigger modal -->


<!-- Modal -->

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Open modal for @fat</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>
<script>
$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var recipient = button.data('whatever')
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
})
</script>
</body>

app/views/products/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Une photo de châton pour attendrir l'être aimé</h1>
</div>

<br>
<body>
  
<div class="container">
  <div class="row">
    <div class="col-sm">
      <img class="card-img-top" src=<%= @product.picture %> alt="Card image cap" style="max-width:100%">  
    </div>
    <div class="col-sm">
      <h2><%= @product.name %></h2>
                    <p><%= @product.description %></p>
                    <hr>
                    <h2 class="text-right"><%= @product.price %> € </h2>
                    <%=link_to "Add to cart", new_line_item_path(@product.id), :class=> "btn btn-primary btn-lg"%>
                    <hr>
    </div>

                