config/routes.rb
Rails.application.routes.draw do
	root 'products#index'

  devise_for :users
	resources :charges
  resources :users
  resources :orders
  resources :carts
  resources :products
    resources :line_items
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
    belongs_to :user
    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum += line_item.total_price
      end
      sum
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    #belongs_to :order

  # LOGIC
   def total_price
     #if valid_quantity_and_price?
       quantity.to_s.to_d * product.price.to_s.to_d
     #else
       #0.0
     #end
   end

  def valid_quantity_and_price?
    !quantity.to_s.strip.empty? && !product.price.to_s.strip.empty?
  end

  # def destroy
  #   @line_item = LineItem.find(params[:id])
  #   @line_item.destroy
  # end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    # enum pay_method: {
    #   'Check' => 0,
    #   'Credit card' => 1,
    #   'Purchase order' => 2
    # }
    belongs_to :user
    # validates :pay_method, :description, presence: true
    # validates :pay_method, inclusion: pay_methods.keys
  
    # LOGIC
    def sub_total
      sum = 0
      line_items.each do |line_item|
        sum += line_item.total_price
      end
      sum
    end
  
    def self.search(search)
      where('name LIKE ?', "%#{search}%")
    end
end

app/models/product.rb
class Product < ApplicationRecord
    # mount_uploader :picture, ProductPictureUploader
    has_many :line_items, dependent: :destroy
    has_many :orders, through: :line_items
  
    def self.search(search)
      where('name LIKE ?', "%#{search}%")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  after_create :create_cart


  puts "$"*60;puts "user.rb called";puts "$"*60

  has_one_attached :avatar #This is for active storage, to use an avatar picture.

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    # after_create :welcome_send
  has_many :orders
  
   def welcome_send
     UserMailer.welcome_email(self).deliver_now
  end

  def create_cart
    puts self
    puts self.id
    Cart.create!(user_id: self.id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find_by(user_id: current_user)
    @line_items = LineItem.where(cart_id: @cart)
    @products = []
    @line_items.each do |line_item|
      @products << Product.find(line_item.product_id)
      end
      puts @products
  end

  def edit
  end

  def update
  end

  def destroy
    
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @amount = 5001
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'EUR',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    puts '$'*60; puts "'home_controller#index' has been called"; puts '$'*60
    #@item_array = Item.all
  end

  
# This method is wrong according to our mentor.
  # def is_connected?(user)
  #   if current_user == user
  #     return true
  #   end
  #   false
  # end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

 before_action :authenticate_user, only: [:show]
 before_action :is_logged_user

  def show
    @user = current_user
    @user_events = User.find(params[:id]).event_admin
  end

end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

    def is_logged_user
      unless current_user.id == params[:id].to_i
        flash[:danger] = "You can only visit your profile."
        redirect_to root_path
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :is_logged_user

  puts '$'*60; puts "'users_controller' has been called"; puts '$'*60

  def index
    puts '$'*60; puts "'users#index' has been called";puts '$'*60
    @users = User.all
  end

  def show
    puts '$'*60; puts "'users#show' has been called"; puts '$'*60
    @user = current_user
    # Change that, according to our mentor: 
    # unless is_connected?(@user)
    #   flash[:alert] = "Restricted access."
    #   redirect_to root_path
    # end
  end

  private

  def authenticate_user
    puts '$'*60; puts "users_controller#authenticate_user' has been called"; puts '$'*60
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

    def is_logged_user
      puts '$'*60; puts "users_controller#is_logged_user' has been called"; puts '$'*60
      unless current_user.id == params[:id].to_i
        flash[:danger] = "You can only visit your profile."
        redirect_to root_path
      end
  end
  
  def is_connected?(user)
    if current_user == user
      return true
    end
    false
  end

  def create_cart
    puts self
    puts self.id
    Cart.create!(user_id: self.id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatonThp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/2b6f635bf2.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand text-dark" href="/">Nectar de châton</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-white" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="<%=new_user_registration_path=%>">Register</a>
          </li>
          <li class="ml-4 nav-item">
            <a href="<%=new_user_session_path=%>">Log in</a>
          </li>
          <% if user_signed_in?%>
            <li class="ml-4 nav-item">
              <a href="<%=user_path(current_user.id)%>">My profile</a>
            </li>

            <li class="ml-4 nav-item">
              <%= link_to("Show cart", cart_path(current_user.id))%>
            </li>

            <li class="ml-4 nav-item">
              <%= link_to("Show products", products_path)%>
            </li>

            <li class="ml-4 nav-item">
              <%= link_to("Log out", destroy_user_session_path, method: :delete)%>
            </li>
          <%end%>

        </ul>
      </div>
    </nav>
    <!-- Add message display for every page -->
    <% puts notice%>
    <% puts alert%>
    <% if notice%>
      <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice %>
      </div>
    <%end%>
    <% if alert%>
      <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= alert %>
      </div>
    <%end%>
    <!-- Don't write anything below this line -->
    <%= yield %>
  </body>
</html>